akaunting/routes/admin.php
    Route::get('invoices/export', 'Sales\Invoices@export')->name('invoices.export');
    Route::resource('invoices', 'Sales\Invoices', ['middleware' => ['date.format', 'money']]);

    Route::get('revenues/{revenue}/duplicate', 'Sales\Revenues@duplicate')->name('revenues.duplicate');
    Route::post('revenues/import', 'Sales\Revenues@import')->name('revenues.import');
    Route::get('revenues/export', 'Sales\Revenues@export')->name('revenues.export');
    Route::resource('revenues', 'Sales\Revenues', ['middleware' => ['date.format', 'money']]);

    Route::get('customers/currency', 'Sales\Customers@currency');
    Route::get('customers/{customer}/duplicate', 'Sales\Customers@duplicate')->name('customers.duplicate');
    Route::post('customers/field', 'Sales\Customers@field')->name('customers.field');
    Route::post('customers/import', 'Sales\Customers@import')->name('customers.import');
    Route::get('customers/export', 'Sales\Customers@export')->name('customers.export');
    Route::get('customers/{customer}/enable', 'Sales\Customers@enable')->name('customers.enable');
    Route::get('customers/{customer}/disable', 'Sales\Customers@disable')->name('customers.disable');
    Route::get('customers/{customer}/currency', 'Sales\Customers@currency')->name('customers.currency');
    Route::resource('customers', 'Sales\Customers');
});

Route::group(['prefix' => 'purchases'], function () {
    Route::get('bills/{bill}/received', 'Purchases\Bills@markReceived')->name('bills.received');
    Route::get('bills/{bill}/cancelled', 'Purchases\Bills@markCancelled')->name('bills.cancelled');
    Route::get('bills/{bill}/paid', 'Purchases\Bills@markPaid')->name('bills.paid');
    Route::get('bills/{bill}/print', 'Purchases\Bills@printBill')->name('bills.print');
    Route::get('bills/{bill}/pdf', 'Purchases\Bills@pdfBill')->name('bills.pdf');
    Route::get('bills/{bill}/duplicate', 'Purchases\Bills@duplicate')->name('bills.duplicate');
    Route::get('bills/addItem', 'Purchases\Bills@addItem')->middleware(['money'])->name('bill.add.item');
    Route::post('bills/import', 'Purchases\Bills@import')->name('bills.import');
    Route::get('bills/export', 'Purchases\Bills@export')->name('bills.export');
    Route::resource('bills', 'Purchases\Bills', ['middleware' => ['date.format', 'money']]);

    Route::get('payments/{payment}/duplicate', 'Purchases\Payments@duplicate')->name('payments.duplicate');
    Route::post('payments/import', 'Purchases\Payments@import')->name('payments.import');
    Route::get('payments/export', 'Purchases\Payments@export')->name('payments.export');
    Route::resource('payments', 'Purchases\Payments', ['middleware' => ['date.format', 'money']]);

    Route::get('vendors/currency', 'Purchases\Vendors@currency');
    Route::get('vendors/{vendor}/duplicate', 'Purchases\Vendors@duplicate')->name('vendors.duplicate');
    Route::post('vendors/import', 'Purchases\Vendors@import')->name('vendors.import');
    Route::get('vendors/export', 'Purchases\Vendors@export')->name('vendors.export');
    Route::get('vendors/{vendor}/enable', 'Purchases\Vendors@enable')->name('vendors.enable');
    Route::get('vendors/{vendor}/currency', 'Purchases\Vendors@currency')->name('vendors.currency');
    Route::get('vendors/{vendor}/disable', 'Purchases\Vendors@disable')->name('vendors.disable');
    Route::resource('vendors', 'Purchases\Vendors');
});

Route::group(['prefix' => 'banking'], function () {
    Route::get('accounts/currency', 'Banking\Accounts@currency')->name('accounts.currency');
    Route::get('accounts/{account}/enable', 'Banking\Accounts@enable')->name('accounts.enable');
    Route::get('accounts/{account}/disable', 'Banking\Accounts@disable')->name('accounts.disable');
    Route::resource('accounts', 'Banking\Accounts', ['middleware' => ['date.format', 'money']]);

    Route::post('transactions/import', 'Banking\Transactions@import')->name('transactions.import');
    Route::get('transactions/export', 'Banking\Transactions@export')->name('transactions.export');
    Route::resource('transactions', 'Banking\Transactions');

    Route::resource('transfers', 'Banking\Transfers', ['middleware' => ['date.format', 'money']]);

    Route::post('reconciliations/calculate', 'Banking\Reconciliations@calculate')->middleware(['money']);
    Route::patch('reconciliations/calculate', 'Banking\Reconciliations@calculate')->middleware(['money']);
    Route::resource('reconciliations', 'Banking\Reconciliations', ['middleware' => ['date.format', 'money']]);
});

Route::group(['prefix' => 'settings'], function () {
    Route::post('categories/category', 'Settings\Categories@category');
    Route::get('categories/{category}/enable', 'Settings\Categories@enable')->name('categories.enable');
    Route::get('categories/{category}/disable', 'Settings\Categories@disable')->name('categories.disable');
    Route::resource('categories', 'Settings\Categories');

    Route::get('currencies/currency', 'Settings\Currencies@currency');
    Route::get('currencies/config', 'Settings\Currencies@config');
    Route::get('currencies/{currency}/enable', 'Settings\Currencies@enable')->name('currencies.enable');
    Route::get('currencies/{currency}/disable', 'Settings\Currencies@disable')->name('currencies.disable');
    Route::resource('currencies', 'Settings\Currencies');

    Route::get('taxes/{tax}/enable', 'Settings\Taxes@enable')->name('taxes.enable');
    Route::get('taxes/{tax}/disable', 'Settings\Taxes@disable')->name('taxes.disable');
    Route::resource('taxes', 'Settings\Taxes');

    Route::group(['as' => 'settings.'], function () {
        Route::get('settings', 'Settings\Settings@index')->name('index');
        Route::patch('settings', 'Settings\Settings@update')->name('update');
        Route::get('company', 'Settings\Company@edit')->name('company.edit');
        Route::get('localisation', 'Settings\Localisation@edit')->name('localisation.edit');
        Route::get('invoice', 'Settings\Invoice@edit')->name('invoice.edit');
        Route::get('default', 'Settings\Defaults@edit')->name('default.edit');
        Route::get('email', 'Settings\Email@edit')->name('email.edit');
        Route::patch('email', 'Settings\Email@update')->name('email.update');
        Route::get('schedule', 'Settings\Schedule@edit')->name('schedule.edit');
    });
});

Route::group(['as' => 'settings.'], function () {
    Route::get('{alias}/settings', 'Settings\Modules@edit')->name('module.edit');
    Route::patch('{alias}/settings', 'Settings\Modules@update')->name('module.update');
});

Route::group(['as' => 'apps.', 'prefix' => 'apps'], function () {
    Route::resource('api-key', 'Modules\ApiKey');

    Route::group(['middleware' => 'api.key'], function () {
        Route::resource('home', 'Modules\Home');

        Route::resource('my', 'Modules\My');

        Route::get('categories/{alias}', 'Modules\Tiles@categoryModules')->name('categories.show');
        Route::get('vendors/{alias}', 'Modules\Tiles@vendorModules')->name('vendors.show');
        Route::get('docs/{alias}', 'Modules\Item@documentation')->name('docs.show');

        Route::get('paid', 'Modules\Tiles@paidModules')->name('paid');
        Route::get('new', 'Modules\Tiles@newModules')->name('new');
        Route::get('free', 'Modules\Tiles@freeModules')->name('free');
        Route::get('search', 'Modules\Tiles@searchModules')->name('search');
        Route::post('steps', 'Modules\Item@steps')->name('steps');
        Route::post('download', 'Modules\Item@download')->name('download');
        Route::post('unzip', 'Modules\Item@unzip')->name('unzip');
        Route::post('install', 'Modules\Item@install')->name('install');

        Route::post('{alias}/reviews', 'Modules\Item@reviews')->name('app.reviews');
        Route::get('{alias}/uninstall', 'Modules\Item@uninstall')->name('app.uninstall');
        Route::get('{alias}/enable', 'Modules\Item@enable')->name('app.enable');
        Route::get('{alias}/disable', 'Modules\Item@disable')->name('app.disable');
        Route::get('{alias}', 'Modules\Item@show')->name('app.show');
    });
});

Route::group(['prefix' => 'install'], function () {
    Route::get('updates', 'Install\Updates@index')->name('updates.index');
    Route::get('updates/changelog', 'Install\Updates@changelog')->name('updates.changelog');
    Route::get('updates/check', 'Install\Updates@check')->name('updates.check');
    Route::get('updates/run/{alias}/{version}', 'Install\Updates@run')->name('updates.run');
    Route::post('updates/steps', 'Install\Updates@steps')->name('updates.steps');
    Route::post('updates/download', 'Install\Updates@download')->middleware('api.key')->name('updates.download');
    Route::post('updates/unzip', 'Install\Updates@unzip')->middleware('api.key')->name('updates.unzip');
    Route::post('updates/copy-files', 'Install\Updates@copyFiles')->middleware('api.key')->name('updates.copy');
    Route::post('updates/migrate', 'Install\Updates@migrate')->name('updates.migrate');
    Route::post('updates/finish', 'Install\Updates@finish')->name('updates.finish');
    Route::post('updates/redirect', 'Install\Updates@redirect')->name('updates.redirect');
});

Route::group(['as' => 'modals.', 'prefix' => 'modals'], function () {
    Route::resource('accounts', 'Modals\Accounts');
    Route::resource('categories', 'Modals\Categories');
    Route::resource('currencies', 'Modals\Currencies');
    Route::resource('customers', 'Modals\Customers');
    Route::resource('vendors', 'Modals\Vendors');
    Route::resource('items', 'Modals\Items');
    Route::patch('invoice-templates', 'Modals\InvoiceTemplates@update')->name('invoice-templates.update');
    Route::resource('invoices/{invoice}/transactions', 'Modals\InvoiceTransactions', ['names' => 'invoices.invoice.transactions', 'middleware' => ['date.format', 'money']]);

akaunting/app/Http/Controllers/Api/Settings/Categories.php
<?php

namespace App\Http\Controllers\Api\Settings;

use App\Abstracts\Http\ApiController;
use App\Http\Requests\Setting\Category as Request;
use App\Jobs\Setting\CreateCategory;
use App\Jobs\Setting\DeleteCategory;
use App\Jobs\Setting\UpdateCategory;
use App\Models\Setting\Category;
use App\Transformers\Setting\Category as Transformer;

class Categories extends ApiController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Dingo\Api\Http\Response
     */
    public function index()
    {
        $categories = Category::collect();

        return $this->response->paginator($categories, new Transformer());
    }

    /**
     * Display the specified resource.
     *
     * @param  Category  $category
     * @return \Dingo\Api\Http\Response
     */
    public function show(Category $category)
    {
        return $this->response->item($category, new Transformer());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  $request
     * @return \Dingo\Api\Http\Response
     */
    public function store(Request $request)
    {
        $category = $this->dispatch(new CreateCategory($request));

        return $this->response->created(route('api.categories.show', $category->id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  $category
     * @param  $request
     * @return \Dingo\Api\Http\Response
     */
    public function update(Category $category, Request $request)
    {
        try {
            $category = $this->dispatch(new UpdateCategory($category, $request));

            return $this->item($category->fresh(), new Transformer());
        } catch(\Exception $e) {
            $this->response->errorUnauthorized($e->getMessage());
        }
    }

    /**
     * Enable the specified resource in storage.
     *
     * @param  Category  $category
     * @return \Dingo\Api\Http\Response
     */
    public function enable(Category $category)
    {
        $category = $this->dispatch(new UpdateCategory($category, request()->merge(['enabled' => 1])));

        return $this->item($category->fresh(), new Transformer());
    }

    /**
     * Disable the specified resource in storage.
     *
     * @param  Category  $category
     * @return \Dingo\Api\Http\Response
     */
    public function disable(Category $category)
    {
        try {
            $category = $this->dispatch(new UpdateCategory($category, request()->merge(['enabled' => 0])));

            return $this->item($category->fresh(), new Transformer());
        } catch(\Exception $e) {
            $this->response->errorUnauthorized($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Category  $category
     * @return \Dingo\Api\Http\Response
     */
    public function destroy(Category $category)
    {
        try {
            $this->dispatch(new DeleteCategory($category));

            return $this->response->noContent();
        } catch(\Exception $e) {
            $this->response->errorUnauthorized($e->getMessage());
        }
    }
}

akaunting/app/Http/Controllers/Api/Settings/Currencies.php
<?php

namespace App\Http\Controllers\Api\Settings;

use App\Abstracts\Http\ApiController;
use App\Http\Requests\Setting\Currency as Request;
use App\Jobs\Setting\CreateCurrency;
use App\Jobs\Setting\DeleteCurrency;
use App\Jobs\Setting\UpdateCurrency;
use App\Models\Setting\Currency;
use App\Transformers\Setting\Currency as Transformer;

class Currencies extends ApiController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Dingo\Api\Http\Response
     */
    public function index()
    {
        $currencies = Currency::collect();

        return $this->response->paginator($currencies, new Transformer());
    }

    /**
     * Display the specified resource.
     *
     * @param  int|string  $id
     * @return \Dingo\Api\Http\Response
     */
    public function show($id)
    {
        // Check if we're querying by id or code
        if (is_numeric($id)) {
            $currency = Currency::find($id);
        } else {
            $currency = Currency::where('code', $id)->first();
        }

        return $this->response->item($currency, new Transformer());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  $request
     * @return \Dingo\Api\Http\Response
     */
    public function store(Request $request)
    {
        $currency = $this->dispatch(new CreateCurrency($request));

        return $this->response->created(route('api.currencies.show', $currency->id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  $currency
     * @param  $request
     * @return \Dingo\Api\Http\Response
     */
    public function update(Currency $currency, Request $request)
    {
        try {
            $currency = $this->dispatch(new UpdateCurrency($currency, $request));

            return $this->item($currency->fresh(), new Transformer());
        } catch(\Exception $e) {
            $this->response->errorUnauthorized($e->getMessage());
        }
    }

    /**
     * Enable the specified resource in storage.
     *
     * @param  Currency  $currency
     * @return \Dingo\Api\Http\Response
     */
    public function enable(Currency $currency)
    {
        $currency = $this->dispatch(new UpdateCurrency($currency, request()->merge(['enabled' => 1])));

        return $this->item($currency->fresh(), new Transformer());
    }

    /**
     * Disable the specified resource in storage.
     *
     * @param  Currency  $currency
     * @return \Dingo\Api\Http\Response
     */
    public function disable(Currency $currency)
    {
        try {
            $currency = $this->dispatch(new UpdateCurrency($currency, request()->merge(['enabled' => 0])));

            return $this->item($currency->fresh(), new Transformer());
        } catch(\Exception $e) {
            $this->response->errorUnauthorized($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Currency  $currency
     * @return \Dingo\Api\Http\Response
     */
    public function destroy(Currency $currency)
    {
        try {
            $this->dispatch(new DeleteCurrency($currency));

            return $this->response->noContent();
        } catch(\Exception $e) {
            $this->response->errorUnauthorized($e->getMessage());
        }
    }
}

akaunting/app/Http/Controllers/Install/Settings.php
<?php

namespace App\Http\Controllers\Install;

use App\Http\Requests\Install\Setting as Request;
use App\Utilities\Installer;
use Illuminate\Routing\Controller;

class Settings extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('install.settings.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     *
     * @return Response
     */
    public function store(Request $request)
    {
        // Create company
        Installer::createCompany($request->get('company_name'), $request->get('company_email'), session('locale'));

        // Create user
        Installer::createUser($request->get('user_email'), $request->get('user_password'), session('locale'));

        // Make the final touches
        Installer::finalTouches();

        // Redirect to dashboard
        $response['redirect'] = route('login');

        return response()->json($response);
    }
}

akaunting/app/Http/Controllers/Settings/Company.php
<?php

namespace App\Http\Controllers\Settings;

use App\Abstracts\Http\Controller;

class Company extends Controller
{
    public function edit()
    {
        return view('settings.company.edit');
    }
}

akaunting/resources/views/settings/settings/index.blade.php
@extends('layouts.admin')

@section('title', trans_choice('general.settings',2))

@section('content')
    <div class="card shadow">
        <div class="card-body">
            <div class="row">
                @permission('read-settings-company')
                    <div class="col-md-4">
                        <a href="{{ route('settings.company.edit') }}">
                            <button type="button" class="btn-icon-clipboard p-2">
                                <div class="row mx-0">
                                    <div class="col-auto">
                                        <div class="badge badge-secondary settings-icons">
                                            <i class="fa fa-building" ></i>
                                        </div>
                                    </div>
                                    <div class="col ml--2">
                                        <h4 class="mb-0">{{ trans_choice('general.companies', 1) }}</h4>
                                        <p class="text-sm text-muted mb-0">{{ trans('settings.company.description') }}</p>
                                    </div>
                                </div>
                            </button>
                        </a>
                    </div>
                @endpermission

                @permission('read-settings-localisation')
                    <div class="col-md-4">
                        <a href="{{ route('settings.localisation.edit') }}">
                            <button type="button" class="btn-icon-clipboard p-2">
                                <div class="row mx-0">
                                    <div class="col-auto">
                                        <div class="badge badge-secondary settings-icons">
                                            <i class="fas fa-map-marker-alt"></i>
                                        </div>
                                    </div>
                                    <div class="col ml--2">
                                        <h4 class="mb-0">{{ trans_choice('general.localisations', 1) }}</h4>
                                        <p class="text-sm text-muted mb-0">{{ trans('settings.localisation.description') }}</p>
                                    </div>
                                </div>
                            </button>
                        </a>
                    </div>
                @endpermission

                @permission('read-settings-invoice')
                    <div class="col-md-4">
                        <a href="{{ route('settings.invoice.edit') }}">
                            <button type="button" class="btn-icon-clipboard p-2">
                                <div class="row mx-0">
                                    <div class="col-auto">
                                        <div class="badge badge-secondary settings-icons">
                                            <i class="fas fa-file-alt"></i>
                                        </div>
                                    </div>
                                    <div class="col ml--2">
                                        <h4 class="mb-0">{{ trans_choice('general.invoices', 1) }}</h4>
                                        <p class="text-sm text-muted mb-0">{{ trans('settings.invoice.description') }}</p>
                                    </div>
                                </div>
                            </button>
                        </a>
                    </div>
                @endpermission

                @permission('read-settings-defaults')
                    <div class="col-md-4">
                        <a href="{{ route('settings.default.edit') }}">
                            <button type="button" class="btn-icon-clipboard p-2">
                                <div class="row mx-0">
                                    <div class="col-auto">
                                        <div class="badge badge-secondary settings-icons">
                                            <i class="fa fa-sliders-h"></i>
                                        </div>
                                    </div>
                                    <div class="col ml--2">
                                        <h4 class="mb-0">{{ trans_choice('general.defaults', 1) }}</h4>
                                        <p class="text-sm text-muted mb-0">{{ trans('settings.default.description') }}</p>
                                    </div>
                                </div>
                            </button>
                        </a>
                    </div>
                @endpermission

                @permission('read-settings-email')
                    <div class="col-md-4">
                        <a href="{{ route('settings.email.edit') }}">
                            <button type="button" class="btn-icon-clipboard p-2">
                                <div class="row mx-0">
                                    <div class="col-auto">
                                        <div class="badge badge-secondary settings-icons">
                                            <i class="fa fa-envelope"></i>
                                        </div>
                                    </div>
                                    <div class="col ml--2">
                                        <h4 class="mb-0">{{ trans('general.email') }}</h4>
                                        <p class="text-sm text-muted mb-0">{{ trans('settings.email.description') }}</p>
                                    </div>
                                </div>
                            </button>
                        </a>
                    </div>
                @endpermission

                @permission('read-settings-schedule')
                    <div class="col-md-4">
                        <a href="{{ route('settings.schedule.edit') }}">
                            <button type="button" class="btn-icon-clipboard p-2">
                                <div class="row mx-0">
                                    <div class="col-auto">
                                        <div class="badge badge-secondary settings-icons">
                                            <i class="fas fa-history"></i>
                                        </div>
                                    </div>
                                    <div class="col ml--2">
                                        <h4 class="mb-0">{{ trans('settings.scheduling.name') }}</h4>
                                        <p class="text-sm text-muted mb-0">{{ trans('settings.scheduling.description') }}</p>
                                    </div>
                                </div>
                            </button>
                        </a>
                    </div>
                @endpermission

                @permission('read-settings-categories')
                    <div class="col-md-4">
                        <a href="{{ route('categories.index') }}">
                            <button type="button" class="btn-icon-clipboard p-2">
                                <div class="row mx-0">
                                    <div class="col-auto">
                                        <div class="badge badge-secondary settings-icons">
                                            <i class="fa fa-folder"></i>
                                        </div>
                                    </div>
                                    <div class="col ml--2">
                                        <h4 class="mb-0">{{ trans_choice('general.categories', 2) }}</h4>
                                        <p class="text-sm text-muted mb-0">{{ trans('settings.categories.description') }}</p>
                                    </div>
                                </div>
                            </button>
                        </a>
                    </div>
                    @endpermission

                @permission('read-settings-currencies')
                    <div class="col-md-4">
                        <a href="{{ route('currencies.index') }}">
                            <button type="button" class="btn-icon-clipboard p-2">
                                <div class="row mx-0">
                                    <div class="col-auto">
                                        <div class="badge badge-secondary settings-icons">
                                            <i class="fa fa-dollar-sign"></i>
                                        </div>
                                    </div>
                                    <div class="col ml--2">
                                        <h4 class="mb-0">{{ trans_choice('general.currencies', 2) }}</h4>
                                        <p class="text-sm text-muted mb-0">{{ trans('settings.currencies.description') }}</p>
                                    </div>
                                </div>
                            </button>
                        </a>
                    </div>
                @endpermission

                @permission('read-settings-taxes')
                    <div class="col-md-4">
                        <a href="{{ route('taxes.index') }}">
                            <button type="button" class="btn-icon-clipboard p-2">
                                <div class="row mx-0">
                                    <div class="col-auto">
                                        <div class="badge badge-secondary settings-icons">
                                            <i class="fas fa-percent"></i>
                                        </div>
                                    </div>
                                    <div class="col ml--2">
                                        <h4 class="mb-0">{{ trans_choice('general.taxes', 2) }}</h4>
                                        <p class="text-sm text-muted mb-0">{{ trans('settings.taxes.description') }}</p>
                                    </div>
                                </div>
                            </button>
                        </a>
                    </div>
                @endpermission

                @foreach($modules as $module)
                    <div class="col-md-4">
                        <a href="{{ url($module['url']) }}">
                            <button type="button" class="btn-icon-clipboard p-2">
                                <div class="row mx-0">
                                    <div class="col-auto">
                                        <div class="badge badge-secondary settings-icons">
                                            <i class="{{ $module['icon'] }}"></i>
                                        </div>
                                    </div>
                                    <div class="col ml--2">
                                        <h4 class="mb-0">{{ $module['name'] }}</h4>
                                        <p class="text-sm text-muted mb-0">{{ $module['description'] }}</p>
                                    </div>
                                </div>
                            </button>
                        </a>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

@push('scripts_start')
    <script src="{{ asset('public/js/settings/settings.js?v=' . version('short')) }}"></script>
@endpush